### ISSUE TITLE
"Backpropagation" in MCTS implementation

### ISSUE THREAD

**Issue by aidmandorky** [algorithmsbooks/decisionmaking#102]
Hello, 

I had another question about the implementation of MCTS for POMDPs given in the book. As I understand it, MCTS consists of four phases: selection, expansion, simulation and backpropagation. 

During the simulation (i.e., rollout) phases, we are at a leaf node of the tree and we run a rollout and note the reward. In the POMDP MCTS algorithm 22.1, this is (if I am not mistaken) given by the final `return` in this code snippet: 
```
for a in 𝒜
N[(h,a)] = 0
Q[(h,a)] = 0.0
end
return π.U(s)
```
where we return the value function estimate by a random rollout. My question is: why don't we update this value of the history in the value function estimate and visit count dictionaries?

**Comment by tawheeler** [comment]
Hello Koundinya - we do not update the visit and value functions for that leaf because they are associated with taking actions that leave that leaf. The rollout (which does not necessarily have to be a rollout, it could just be an approximate value function) does not constitute taking an action in the MCTS tree.

Note that we do update the values of all of the leaf's parents. We just leave the new leaf with zero visits and zero actions in all of its own successors.

**Comment by aidmandorky** [comment]
Thank you so much for your clarification! This makes sense.
