### ISSUE TITLE
Suggestion for line plot in Example 9.8

### ISSUE THREAD

**Issue by wuzh07** [algorithmsbooks/decisionmaking#106]
The colors of "random rollout" (102,110,185) and "lookahead" (25,117,185) in the line plot in Example 9.8 are confusing for individuals with red-green color blindness (like me). It is greatly appreciated if a color blind-friendly palette is adopted or legends are diversified in different aspects (e.g. color, marker ...). Thank you very much.

**Comment by mykelk** [comment]
Thanks for the note! I agree, those two lines look very similar in color (even for those without colorblindness). As mentioned in the acknowledgment section, we optimized the general color scheme to be colorblind friendly, but this line will need some work. I'll assign Tim to this issue since he has the keenest sense of aesthetics and might have some thoughts on the best correction.

**Comment by tawheeler** [comment]
Hello wuzh07, I am changing the line plot to have varied marker types:
![image](https://github.com/algorithmsbooks/decisionmaking/assets/3334079/4bbd4cca-8151-4bba-9705-d4e0a6b86dbd)

Hope that helps!

**Comment by tawheeler** [comment]
Please let me know if you would like to be acknowledged, in which case I would need your first and last name.

**Comment by tawheeler** [comment]
@wuzh07, could you please let us know what you think of this use of orange instead of the offending purple line? This plot would let us keep our consistent style of only using circular markers.

![image](https://github.com/algorithmsbooks/decisionmaking/assets/3334079/42a68620-231a-4971-b1c7-6770a235efa7)

**Comment by wuzh07** [comment]
@tawheeler The updated one is much better for me and I can tell different lines easily. Thank you again for your consideration.

**Comment by tawheeler** [comment]
Perfect, we'll go with that then.
