### ISSUE TITLE
Exercise 22.3 - Inconsistent based on Algorithm 22.2 and incorrect observation probabilities

### ISSUE THREAD

**Issue by dylan-asmar** [algorithmsbooks/decisionmaking#108]
As written, exercise 22.3 isn't consistent with algorithm 22.2 and can cause a bit of confusion. I also think there might be an error with the provided solution and the provided observation probabilities.

I understand that the order we use for the states and observations isn't critical as long as we are consistent and maintain the determinized aspect of the algorithm. However, the `successor` function in Algorithm 22.2 iterates over $s^\prime$ and $o$ by using `product`. Therefore, that would imply an order of $(s_1, o_1), (s_2, o_1), (s_3, o_1), \dots$ would be used.

Even if we aren't considering that order and skipping over transitioning to $s_1$ (from the provided transition probabilities, we know $T(s_1 \mid s_1, a_3) \leq 0.15$ but we can't determine it based on not knowing the number of states), we aren't provided the appropriate observation probabilities. Our observation function is of the form $O(o \mid s^\prime, a)$. However, we are given $O(\cdot \mid s_1, a_3)$ instead of $O(\cdot \mid s_2, a_3)$ and $O(\cdot \mid s_3, a_3)$.

**Comment by tawheeler** [comment]
Yes, this needs to be updated since it has the same mistake the other issue you reported has. That required defining some additional observation values. 

![image](https://github.com/algorithmsbooks/decisionmaking/assets/3334079/b00f9f97-22fa-4088-a05c-4c9b30dadc2e)

We can't change pagination, so adding something to the effect of "for this problem with 2 states and 2 actions" was instead injected into Example 22.5:

![image](https://github.com/algorithmsbooks/decisionmaking/assets/3334079/326677d0-3a80-4aca-8307-d84fd8868b8b)

Thanks!
