### ISSUE TITLE
Eq 11.16 indexing

### ISSUE THREAD

**Issue by mykelk** [algorithmsbooks/decisionmaking#113]
[p. 237] Eq 11.16. To resolve indexing issue into trajectory, the right hand side should be
$p(s^{(1)}) (\prod_{k=1}^{d-1} T(s^{(k+1)} \mid s^{(k)}, a^{(k)}))(\prod_{k=1}^d \pi_{\vec \theta} (a^{(k)} \mid s^{(k)}))$

Do you agree @tawheeler ? If so, I'll fix.

**Comment by mykelk** [comment]
Similar issue in eq. 11.17 and 11.18. I think in both of those we should go to $d-1$?

**Comment by tawheeler** [comment]
If we have a 2-step trajectory with tuples (s1, a1, s2, a2, s3), then we have:
p(trajectory) = p(s1) * p(a1 | s1) * T(s2 | s1, a1) * p(a2 | s2) * T(s3 | s2, a2), which is equal to:
p(trajectory) = p(s1) * [T(s2 | s1, a1) * p(a1 | s1)] * [T(s3 | s2, a2) * p(a2 | s2)], which can be written like we have it in the book:
p(trajectory) = p(s1) * sum_{k=1, 2} T(s_k+1 | s_k, a_k) * p(a_k | s_k)

We have the same number of transition calls as policy calls, so having two separate products with different bounds wouldn't work.

We use `d` to represent the `depth`, which is the _number of actions_, not the index of the last state. In this case, we have 2 actions and it works out.

So I think the current text is correct.

**Comment by mykelk** [comment]
I like the idea of not changing the text and I think it is possible to define the trajectory to include s3, but I think Alg. 11.1 would not include the final s3. I think including s3 would also break Alg 11.4 in its calculation of R and ∇U. Right?

**Comment by josh0tt** [comment]
I think the $d+1$ notation makes more sense. 

Based on the `rollout` function in Algorithm 9.1 it takes the initial state as an argument. We then proceed to sample $d$ actions which results in a total of $d+1$ states (since we start with an initial state).

Another way to see this is in Figure 9.1 where at a depth of 2 we have two "layers" of actions but actually 3 "layers" of states total since we start with an initial state. I think this matches up better as @tawheeler described the depth indicating the number of actions, not the index of the last state.

But I do see the issue in Alg 11.1-11.4. I think modifying Algorithm 11.1 to

```
function simulate(𝒫::MDP, s, π, d) 
    τ = []
    for i = 1:d 
        a = π(s)
        s′, r = 𝒫.TR(s,a)
        push!(τ, (s,a,r)) 
        s = s′
    end  
    push!(τ, (s, nothing, nothing))  # Final state, action and reward are 'nothing'
    return τ
end 
```

We include $s^{(d+1)}$ with `nothing` for the action and reward to signify that no action is taken, and no reward is received after the final state.

Then in 11.2, 11.3, and 11.4 we just do 
```
R(τ) = sum(r * γ^(k-1) for (k, (s, a, r)) in enumerate(τ[1:d]))
``` 
instead of 
```
R(τ) = sum(r * γ^(k-1) for (k, (s, a, r)) in enumerate(τ))
``` 
as well as
```
∇U(τ) = sum(∇logπ(θ, a, s) for (s, a, _) in τ[1:d]) * R(τ)
```
 in 11.4. The last line would only cover stochastic policies though. 

Thoughts?

**Comment by tawheeler** [comment]
Thanks Josh, that helps me understand what issue we're talking about.


In Alg 11.4, first we need to compute R(τ), which is the discounted reward over rollout states. For a problem with d=3, this should be:

R(τ) = R(s1,a1) + γ*R(s2,a2) + γ^2*R(s3,a3)

We also need to compute ∇U(τ), which as we discussed above per eq 11.15 is:

∇U(τ) = ∇logπ(θ, a1, s1) + ∇logπ(θ, a2, s2) + ∇logπ(θ, a3, s3)

At no point do we need s4, so it seems fine that it isn't included in `simulate` from that perspective.

Algorithm 11.4 does not support deterministic policy gradients, so I'm not worried about that.

**Comment by josh0tt** [comment]
That makes sense to me. I think the only discrepancy then would be that the rollout trajectory expected by 11.16 would be (s1, a1, s2, a2, s3, a3, s4), but the trajectory returned from the current implementation of `simulate` would be (s1, a1, s2, a2, s3, a3) -- technically, ((s1, a1, r1), (s2, a2, r2), (s3, a3, r3)). Maybe that's cleaner than having `push!(τ, (s, nothing, nothing))` but I think it might be one of the sources of confusion for the 228 students.

**Comment by tawheeler** [comment]
How about we get around this without widespread changes by changing `simulate` to return (s,a,r,s') tuples instead? The existing code that iterates would continue to work: `for (s,a,r) in τ` would correctly grab only the first 3 entries.

**Comment by mykelk** [comment]
Whoa. I didn't realize it would pull our just the first three elements. We do end up using 33% more memory for this, but we care more about the algorithms than about efficiency. Would this, though, result in a bit of a deviation from the math in the book? What are the implications here on the indexing in the equations?

**Comment by tawheeler** [comment]
> Whoa. I didn't realize it would pull our just the first three elements. 

Yup! We already make use of this in Alg 11.6 with
```
denom(τ) = sum(ℓ(a,s,k).^2 for (k,(s,a)) in enumerate(τ))
```

> Would this, though, result in a bit of a deviation from the math in the book? What are the implications here on the indexing in the equations?

My understanding of the problem is that `simulate` does not provide the final state. I do not see eq 11.16 as being written with (k+1) syntax vs. s' syntax as being an issue. Readers are smart enough to know that sometimes we have updates (x' <- f(x)) and sometimes we have integer indexing (x[k+1] <- f(x[k]). We also don't evaluate eq 11.16.

>  We do end up using 33% more memory for this, but we care more about the algorithms than about efficiency. 

The book is already structured around denser, simpler code. If we care about memory and layout efficiency, we'd have something like:

```
struct RolloutResult{S,A,R}
   states::Vector{S} # of length d+1, with states[1] being the initial state
   actions::Vector{A} # of length d
   rewards::Vector{R} # of length d
end
```

Or, in all honesty, we'd be doing batched rollouts that populate large tensors.
We purposely didn't do that because it is verbose and distracts from the core ideas.

> --

If eq 11.16 is the main source of confusion, then we could just add a sidenote there that says "The `simulate` implementation does not provide the terminal state, so the final T(s' | s, a) cannot be evaluated with one of `simulate`'s trajectories. The method could be modified to return that state if evaluating pθ (τ ) were needed."

**Comment by mykelk** [comment]
I suppose the main source of confusion is eq. 11.16-18. How would that be changed?

**Comment by tawheeler** [comment]
Eq 11.17 and 11.18 exist to both show that the log likelihood trick does not work for deterministic policies (thus emphasizing how nice it is that Eq 11.16 does not have T(s' | s, a)) and to present that equation for someone should they wish to implement their own algorithm for optimizing a deterministic policy. I don't think we optimize deterministic policies in the chapter --  our implementations are for stochastic policies. 

Eq 11.16 correctly shows the likelihood of a trajectory. The discrepancy is that `simulate` in Alg 11.1 does not produce a data structure containing s[d+1]. There is nothing incorrect in eq 11.16 itself.

We never evaluate eq 11.16 in our algorithms. The algorithms instead evaluate its gradient, which as we point out (because it is very important), the log likelihood trick means we don't need to evaluate the transition function.

It is perfectly normal for an implementation like Alg 11.1 to be suitable for what it is used for. If we had a clean way to update it that did not involve changing a bunch of algorithms (and introduce more indexing notation that adds to confusion) then I would be for it, but we don't have a great solution.

Given that the equations are correct and the algorithms are correct as far as I've seen, I'd advocate for a sidenote either at 11.16 or in Alg 11.1: "This implementation does not store the final state, as it is not typically needed in the ensuing algorithms. The final state after taking `d` actions should generally be thought of as being part of a trajectory rollout".

**Comment by josh0tt** [comment]
I like the idea of adding a sidenote at either 11.16 or Alg 11.1

**Comment by mykelk** [comment]
Sounds good. I can take a crack for review.

**Comment by tawheeler** [comment]
I'm going to suggest a commit now.
I don't think we're allowed to change the sidenote numbering, so I'll suggest a new statement in the algorithm caption.
