### ISSUE TITLE
Line numbers in algorithms

### ISSUE THREAD

**Issue by zsunberg** [algorithmsbooks/decisionmaking#51]
Not sure if this has already been discussed, but I think it would be useful to add line numbers in algorithms.

**Comment by mykelk** [comment]
We didn't do it for Algorithms for Optimization. I don't recall anyone asking for it since it came out in 2019 (or back when it was a course reader). Since the functions are generally pretty short, we don't really have to refer to the line numbers. In neither of the books did we find a need to do this within the text.

**Comment by zsunberg** [comment]
I have wished for it several times. For instance, when answering questions on Piazza, I have wanted to refer to lines in Algorithm 9.6. Right now, I have to write out the actual code in the line I am referring to, which is cumbersome when discussing more than one line.

**Comment by mykelk** [comment]
Ah, interesting. It hasn't come up for me---or maybe I just said things like "the first line in the for loop". I'll discuss with Tim and Kyle.

**Comment by mykelk** [comment]
After some discussion, we've decided not to do it for this book.
