### ISSUE TITLE
How should the problem be defined?

### ISSUE THREAD

**Issue by AlexandrParkhomenko** [algorithmsbooks/decisionmaking#77]
Hello. I have another question about basic things. 
There is an Example 10.1 on Page 213
```julia
b, d, n_rollouts = Normal(0.3,0.1), 10, 3
U = MonteCarloPolicyEvaluation(𝒫, b, d, n_rollouts)
```
ERROR: LoadError: UndefVarError: 𝒫 not defined

Please explain how should the problem be defined?

**Comment by tawheeler** [comment]
Hello Alexandr,

The method takes an MDP struct as defined in alg 7.1:
![Selection_355](https://user-images.githubusercontent.com/3334079/124794668-1b8caf00-df04-11eb-9a39-78f17b70d370.png)

That being said, because we don't use type templating you can use any struct that provides the necessary fields.

Cheers,
-Tim

**Comment by tawheeler** [comment]
Also, the [DecisionMakingProblems.jl repo](https://algorithmsbooks.github.io/DecisionMakingProblems.jl/) contains implementations for the problems used in the book.
